name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: "*/55 * * * *" # every 55th minute

jobs:
  ##############################################################################
  upvote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: actions/checkout@v4

      - run: yarn run test
